### PR TITLE
Easy ui for handling base functionalities of taskscheduler

### PR DESCRIPTION
**Pull request by OliverBLMS**
Maybe this can add even more simplicity to the taskscheduler.
A light-weight rstudio Addin with a mini-UI.

### CODE REVIEW

**Comment by OliverBLMS** [comment]
Slightly different approach: I use a "central" repository which will be located in the package dir. So all uploaded Rscript will be copied to this location. It will use the file names to execute create, stop, delete.
Of course delete will trigger a deletion of the task itself, and also a deletion from the "central" repository.

**Comment by jwijffels** [comment]
Great! Exactly what I requested at http://www.bnosac.be/index.php/blog/56-taskscheduler-r-package-to-schedule-r-scripts-with-the-windows-task-manager :)

First time I see such an new addin feature of RStudio. I'll see how to incorporate it inside the package (R  CMD check gives me currently quite some warnings. 

Maybe we can use getActiveDocumentContext() to get the file pointing to the current file open in RStudio. 
I'll try to incorporate it!

**Comment by jwijffels** [comment]
Thanks for the code!
Merged it and made sure r cmd check does not complain. Added hour and Rscript extraargs argument. 
Do test!

**Comment by OliverBLMS** [comment]
Glad to hear this! 
Just figured this out. When updating a package the whole package folder will be overwritten. This is something that we don't want, because this folder also holds the script "repository". Is there a way to avoid this, only for the subfolder extdata?

**Comment by jwijffels** [comment]
if you install a package, there is no way to not overwrite the folders of this package.
what we can do to fix this is make sure the RscriptRepository is `another`directory which could be set in the RStudio add-in and saved to disk so that we can automatically use it when loading the scheduleR package.
The taskschedulerAddin function currently already has this argument RscriptRepository for that reason. Need to implement the extra argument in the rstudio add-in + make sure it is saved to disk so that we don't have to fill it in every time.

**Comment by jwijffels** [comment]
added this functionality

**Comment by OliverBLMS** [comment]
This has never been so easy :+1:

**Comment by jwijffels** [comment]
this also makes my day and speeds up some tasks. will make a blog post about it.

**Pull request merged**
