### PR TITLE
Options argument was added for Rscript.exe in taskscheduler_create() …

### PR DESCRIPTION
**Pull request by cemoze**
For detailed information about this pull request, issue https://github.com/bnosac/taskscheduleR/issues/97 of the taskscheduleR repository can be viewed.

### CODE REVIEW

**Comment by jwijffels** [comment]
Thanks. Can you also update the roxygen documentation of the argument and the resulting rd file

**Comment by cemoze** [comment]
I have just updated the roxygen documentation and the resulting rd file.

**Comment by jwijffels** [comment]
Thanks!

**Comment by jwijffels** [comment]
FYI. I pushed it to cran yesterday.

**Pull request merged**
